# Enable <t_CO> colors
case "$TERM" in
    xterm*) TERM=xterm-256color
esac 

# enable sensitive matching
CASE_SENSITIVE="true"

#nes configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=100000
EDITOR=vim
bindkey -e
# End of lines configured by zsh-newuser-install
autoload -U colors && colors
source /usr/share/zsh/share/antigen.zsh 

#composer bins
PATH=$PATH:~/.config/composer/vendor/bin:~/Code/zscreen/src:

# ruby bins
# PATH="$(ruby -rubygems -e 'print Gem.user_dir')/bin:$PATH"

#Add Android Path
PATH=$PATH:/opt/android-sdk/tools/:

#Meteor
PATH=$PATH:$HOME/.meteor

#Go lang
PATH="$PATH:$HOME/go/bin"

# Android Studio
export JAVA_HOME=/usr/lib/jvm/java-7-jdk
PATH=$PATH:/opt/android-sdk/platform-tools

# Node Vars
export NODE_ENV=development

# POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status context)
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""

POWERLEVEL9K_TIME_FOREGROUND='015'
POWERLEVEL9K_TIME_BACKGROUND='240'

POWERLEVEL9K_DIR_HOME_BACKGROUND='239'
POWERLEVEL9K_DIR_HOME_FOREGROUND='white'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='239'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='white'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='239'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='white'

POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='229'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='239'

POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='015'
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='088'

POWERLEVEL9K_STATUS_VERBOSE=false

antigen bundle common-aliases
antigen bundle git
antigen bundle npm
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle djui/alias-tips

antigen use oh-my-zsh

antigen theme bhilburn/powerlevel9k powerlevel9k

antigen apply

alias ls='ls --color --group-directories-first'

alias fucking='sudo'
alias subl='subl3'
alias so='subl3 -a'

# cd shortcuts
alias cB="cd ~/Code/bayer/dftams-frontend"

alias art='php artisan'
alias artS="php artisan migrate:refresh --seed"
alias comdump='composer dump-autoload'

alias gis="git status"
alias gia="git add ."
alias gil="git log --oneline --graph"

alias save-power="sudo cpupower frequency-set -u 800Mhz"
alias full-power="sudo cpupower frequency-set -g performance"
alias eV="vim ~/.vimrc"
alias eZ="vim ~/.zshrc"
alias sZ="source ~/.zshrc"
alias eI="vim ~/.config/i3/config"
alias eH="sudo vim /etc/hosts"
alias rD="sudo systemctl start docker"
alias Dstop="docker stop \$(docker ps -q)"
alias Dclear="docker stop \$(docker ps -a -q) && docker rm \$(docker ps -a -q)"

alias Cs=". control start"
alias Cd=". control down"
alias Cb=". control rebuild"
alias Cp=". control ps"
alias Cw=". control w"
alias Ct=". control run codecept run"
alias Cr=". control run"
alias Cart=". control run php artisan"

alias C=". control"

alias gulpw="gulp && gulp watch"
alias gw="gulp watch"

alias W="wunderline"

function pass() {
    if ! [[ $1 =~ '^[0-9]+$' ]] ; then
        echo "pass needs a number argument" >&2
    else
        cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $1 | head -n 1
    fi
}

figlet -ctf small  -k "TecBeast"

alias dcup="docker-compose up -d"
alias dcdn="docker-compose down"
alias dclf="docker-compose logs -f"

alias wp="docker-compose -f docker-compose.yml -f docker-compose.wpcli.yml run --rm wpcli"
alias wp_fast="wp --skip-packages --skip-plugins --skip-themes"

yd_dc() { git archive --remote git@git.yesdevs.com:oktron/docker-compose.git --format tar master | tar -x; rm -f .gitignore; }
yd_gc() { git clone "git@git.yesdevs.com:$1.git" $2; }
yd_sr() { wp_fast search-replace $1 $2 --recurse-objects --skip-columns=guid --all-tables; }

alias yd_dcmysql="mysql -uroot -pmysql -h127.0.0.1"
alias yd_dcmysqldump="mysqldump -uroot -pmysql -h127.0.0.1"

source /usr/share/nvm/init-nvm.sh
