# Enable <t_CO> colors
case "$TERM" in
    xterm*) TERM=xterm-256color
esac 

# enable sensitive matching
CASE_SENSITIVE="true"

#nes configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=100000
bindkey -e
# End of lines configured by zsh-newuser-install
autoload -U colors && colors
source /usr/share/zsh/share/antigen.zsh 

antigen-use oh-my-zsh

antigen bundle common-aliases
antigen bundle git
antigen bundle npm
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle djui/alias-tips
antigen bundle supercrabtree/k

antigen theme bhilburn/powerlevel9k powerlevel9k

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status context time)
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""

POWERLEVEL9K_TIME_FOREGROUND='015'
POWERLEVEL9K_TIME_BACKGROUND='240'

POWERLEVEL9K_DIR_HOME_BACKGROUND='239'
POWERLEVEL9K_DIR_HOME_FOREGROUND='white'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='239'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='white'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='239'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='white'

POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='229'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='239'

POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='015'
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='088'

POWERLEVEL9K_STATUS_VERBOSE=false

antigen apply

alias ls='ls --color --group-directories-first'

alias fucking='sudo'
alias subl='subl3'
alias so='subl3 -a'
alias cTVS='cd ~/Code/cellular/tvspielfilm_live'
alias cUMB='cd ~/Code/cellular/unitymedia_bestellstrecke/'
alias cW1TV='cd ~/Code/web1tv'

alias art='php artisan'
alias artS="php artisan migrate:refresh --seed"
alias comdump='composer dump-autoload'

alias gis="git status"
alias gia="git add ."
alias gil="git log --oneline --graph"

alias save-power="sudo cpupower frequency-set -u 800Mhz"
alias full-power="sudo cpupower frequency-set -g performance"
alias eV="vim ~/.vimrc"
alias eZ="vim ~/.zshrc"
alias sZ="source ~/.zshrc"
alias eI="vim ~/.i3/config"
alias eH="sudo vim /etc/hosts"
alias rD="sudo systemctl start docker"
alias Dstop="docker stop \$(docker ps -q)"
alias Dclear="docker stop \$(docker ps -a -q) && docker rm \$(docker ps -a -q)"
alias k="k -h"

alias rWeb1TV="VBoxManage startvm web1tv --type headless"
alias ssWeb1TV="ssh root@web1tv.dev"

alias Cs="./control start"
alias Cd="./control down"
alias Cb="./control rebuild"
alias Cp="./control ps"
alias Cw="./control w"
alias Ct="./control run codecept run"
alias Cart="./control run php artisan"
alias Cr="./control run"

alias gulpw="gulp && gulp watch"
alias grb="grunt build"

alias sCellular="xrandr --output HDMI1 --mode 2560x1440 &&  xrandr --output HDMI1 --right-of eDP1 && xrandr --output VGA1 --right-of HDMI1"

#composer bins
PATH=$PATH:~/.config/composer/vendor/bin:~/Code/zscreen/src:
PATH="$(ruby -rubygems -e 'print Gem.user_dir')/bin:$PATH"

#Add Android Path
PATH=$PATH:/opt/android-sdk/tools/:

#Meteor
PATH=$PATH:$HOME/.meteor

figlet -ctf small  -k "TecBeast"

# Android Studio
export JAVA_HOME=/usr/lib/jvm/java-7-jdk
PATH=$PATH:/opt/android-sdk/platform-tools

# Enable in cmd calc 
calc () {
    bc -l <<< "$@"
}

# Node Vars
export NODE_ENV=development
