#!/usr/bin/sh

SCRIPTPATH=$(readlink -f "$0")
BASEDIR=$(dirname "$SCRIPTPATH")
echo $BASEDIR

DOTFILES=${BASEDIR}/dotfiles/*

setDotfile () {
	echo "Set link from $1 to $2"
	ln -s $1 $2
}

# Set root dotfiles
for f in $DOTFILES
do
	TARGETPATH=/root/.$(basename $f)
	# Check if file exists
	if [ -e "$TARGETPATH" ]; then
		echo "$TARGETPATH already exists"
		if [ ! -L "$TARGETPATH" ] || [ ! "$(readlink -- "$TARGETPATH")" = $f ]; then
			echo "Something is wrong with the link $TARGETPATH; fixing ..."
			mv $TARGETPATH $TARGETPATH.bak
			setDotfile $f $TARGETPATH
		fi

	else
		setDotfile $f $TARGETPATH 
	fi
done
